name: flutter_gradient_app_bar_plus
description: The official AppBar, with a more colorful twist. Add gradients to spice up your application and make it beautiful. This is a Fork of flutter_gradient_app_bar
version: 0.4.1
homepage: https://github.com/shawn-grant/FlutterGradientAppBar

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.8.1

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
